name: Build and Push Docker image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM from go.sum
        run: |
          # Extract the downloaded Ollama source
          LATEST=$(gh api repos/ollama/ollama/releases/latest --jq '.tag_name')
          EXTRACTED_DIR="ollama-${LATEST#v}"
          
          # Generate SBOM from the extracted Go project
          syft $EXTRACTED_DIR -o cyclonedx-json=bom.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ env.REPO }}:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ env.REPO }}:latest